INSERT INTO TBL_STUDENT(NAME, COURSE) VALUES ('Glauco Todesco','Computação');
INSERT INTO TBL_STUDENT(NAME, COURSE) VALUES ('Maria Silva','Letras');
INSERT INTO TBL_STUDENT(NAME, COURSE) VALUES ('Fernanda Arruda','Eventos');